import type { FormKitNode } from "@formkit/core";

/**
 * @privateRemarks
 * This file was generated by the FormKit CLI and should not be manually
 * edited unless you’d like to "eject" from the CLI’s ability to update it.
 *
 * @checksum - 145df0a4dda3f372a5c7b2036c584668d9212af4b6a8dc0f957b748b7d125f13
 * @variables -
 * @theme - regenesis
 **/

/**
 * This is the theme function itself, it should be imported and used as the
 * config.rootClasses function. For example:
 *
 * ```js
 * import { theme } from './formkit.theme'
 * import { defineFormKitConfig } from '@formkit/vue'
 *
 * export default defineFormKitConfig({
 *   config: {
 *     rootClasses: theme
 *   }
 * })
 * ```
 **/
export function rootClasses(
  sectionName: string,
  node: FormKitNode
): Record<string, boolean> {
  const key = `${node.props.type}__${sectionName}`;
  const semanticKey = `formkit-${sectionName}`;
  const familyKey = node.props.family
    ? `family:${node.props.family}__${sectionName}`
    : "";
  const memoKey = `${key}__${familyKey}`;
  if (!(memoKey in classes)) {
    const sectionClasses = classes[key] ?? globals[sectionName] ?? {};
    sectionClasses[semanticKey] = true;
    if (familyKey in classes) {
      classes[memoKey] = { ...classes[familyKey], ...sectionClasses };
    } else {
      classes[memoKey] = sectionClasses;
    }
  }
  return classes[memoKey] ?? { [semanticKey]: true };
}

/**
 * These classes have already been merged with globals using tailwind-merge
 * and are ready to be used directly in the theme.
 **/
const classes: Record<string, Record<string, boolean>> = {};

/**
 * Globals are merged prior to generating this file — these are included for
 * any other non-matching inputs.
 **/
const globals: Record<string, Record<string, boolean>> = {
  outer: {
    group: true,
    "min-w-0": true,
    grow: true,
    "mb-4": true,
    "data-[disabled]:select-none": true,
    "data-[disabled]:opacity-50": true,
    "text-base": true,
  },
  label: {
    block: true,
    "text-neutral-700": true,
    "mb-1": true,
    "dark:text-neutral-300": true,
    "text-sm": true,
    "font-medium": true,
    "leading-none": true,
    "peer-disabled:cursor-not-allowed": true,
    "peer-disabled:opacity-70": true,
  },
  legend: {
    block: true,
    "text-neutral-700": true,
    "text-sm": true,
    "font-bold": true,
    "dark:text-neutral-300": true,
  },
  input: {
    flex: true,
    "h-10": true,
    "w-full": true,
    "rounded-md": true,
    border: true,
    "border-slate-200": true,
    "bg-white": true,
    "px-3": true,
    "py-2": true,
    "text-sm": true,
    "ring-offset-white": true,
    "file:border-0": true,
    "file:bg-transparent": true,
    "file:text-sm": true,
    "file:font-medium": true,
    "placeholder:text-slate-500": true,
    "focus-visible:outline-none": true,
    "focus-visible:ring-2": true,
    "focus-visible:ring-slate-950": true,
    "focus-visible:ring-offset-2": true,
    "disabled:cursor-not-allowed": true,
    "disabled:opacity-50": true,
    "dark:border-slate-800": true,
    "dark:bg-slate-950": true,
    "dark:ring-offset-slate-950": true,
    "dark:placeholder:text-slate-400": true,
    "dark:focus-visible:ring-slate-300": true,
  },
  prefixIcon: {
    flex: true,
    "items-center": true,
    "-ml-1": true,
    "mr-2": true,
    "text-base": true,
    "h-[1em]": true,
    "w-[1em]": true,
    "shrink-0": true,
    "[&>svg]:w-full": true,
  },
  suffixIcon: {
    flex: true,
    "items-center": true,
    "-mr-1": true,
    "ml-2": true,
    "text-base": true,
    "h-[1em]": true,
    "w-[1em]": true,
    "shrink-0": true,
    "[&>svg]:w-full": true,
  },
  loaderIcon: {
    "animate-spin": true,
    flex: true,
    "items-center": true,
    "my-auto": true,
    "ml-2": true,
    "text-base": true,
    "text-neutral-500": true,
    "h-[1em]": true,
    "w-[1em]": true,
    "shrink-0": true,
    "[&>svg]:w-full": true,
  },
  loadMoreInner: {
    flex: true,
    "text-sm": true,
    "text-neutral-500": true,
    "p-2": true,
    "items-center": true,
    "justify-center": true,
    "[&>span]:mr-2": true,
  },
  help: {
    "text-neutral-500": true,
    "text-xs": true,
    "dark:text-neutral-400": true,
  },
  message: {
    "text-red-600": true,
    "mb-1.5": true,
    "text-xs": true,
    "dark:text-red-400": true,
  },
  overlay: {
    "text-neutral-700": true,
    "dark:text-neutral-300": true,
  },
  overlayPlaceholder: {
    "text-neutral-400": true,
    "dark:text-neutral-400/50": true,
  },
  overlayLiteral: {
    "text-neutral-700": true,
    "dark:text-neutral-300": true,
  },
  overlayChar: {
    "text-neutral-700": true,
    "dark:text-neutral-300": true,
  },
  overlayEnum: {
    "text-neutral-700": true,
    "dark:text-neutral-300": true,
  },
};
